singleServerConfig:
  address: "redis://localhost:6379"
  password: ""
  database: 0
  connectionMinimumIdleSize: 10
  connectionPoolSize: 64
  idleConnectionTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
